services:

  server:
    image: index.docker.io/norbertle/savemyrpg
    container_name: smrpg_server
    networks:
      - network1
    ports:
      - 443:443
    volumes:
      - /root/smrpg_docker/bg3_saves:/bg3_saves
      - /root/smrpg_docker/serverdata:/serverdata
      - /root/smrpg_docker/ssl:/ssl

  db:
    image: postgres
    container_name: smrpg_db
    restart: always
    ports:
      - 5432:5432
    networks:
      - network1
    volumes:
      - /root/smrpg_docker/bg3_saves:/bg3_saves
      - /root/smrpg_docker/dbdata:/dbdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ninjame
      POSTGRES_DB: default
      PGDATA: /dbdata
  watchtower:
    image: index.docker.io/containrrr/watchtower:latest
    container_name: watchtower
    networks:
      - network1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json
    command: --interval 30 smrpg_server
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: >
        discord://8FIetuxRmMID-1Ebf0X1MgtfafUconwq2Uba2Mj5ncfKOOBmjDKt5w79bqZgf8QSRVjp@1141045180984721408 discord://8FIetuxRmMID-1Ebf0X1MgtfafUconwq2Uba2Mj5ncfKOOBmjDKt5w79bqZgf8QSRVjp@1096112705968029706
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}

networks:
  network1:
    name: smrpgnet
    external: true
