services:

  server:
    image: savemyrpg-production
    networks: 
      - network1
    ports:
      - 8100:8100
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks: 
      - network1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ninjame
      POSTGRES_DB: default
      PGDATA: /dbdata
      

    volumes:
      - c:\Users\brent\Documents\Programming\SaveMyRPGServer\bg3_saves:/bg3_saves
      - c:\Users\brent\Documents\Programming\SaveMyRPGServer\db_initialize.sql:/db_scripts/db_initialize.sql
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run -d
    env_file: tunnel.env
    restart: always
    container_name: tunnel
    networks: 
      - network1
    depends_on:
      - db

networks:
  network1:
    name: smrpg
    external: true