# Dockerfile.db

FROM ubuntu:22.04

RUN apt-get update \
  && apt-get install -y curl
RUN apt install -y software-properties-common gnupg apt-transport-https ca-certificates
RUN curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \ 
   gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
   --dearmor
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list

RUN apt update -y
RUN apt install -y mongodb-org && apt update -y
RUN ps --no-headers -o comm 1
COPY mongod.conf /etc/mongod.conf
EXPOSE 8200
CMD ["systemctl daemon-reload && systemctl start mongod"]