# Dockerfile.production

FROM golang:1.20-bullseye as builder

ENV APP_HOME /go/src/savemyrpgserver

WORKDIR "$APP_HOME"
COPY src/ .
RUN go mod download
RUN go mod verify
RUN go build -o savemyrpgserver
RUN go install

FROM golang:1.20-bullseye

ENV APP_HOME /go/src/savemyrpgserver
RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"
COPY src/ .
COPY --from=builder "$APP_HOME"/savemyrpgserver $APP_HOME

EXPOSE 8100
CMD ["./savemyrpgserver"]

